# Generated by Django 3.1.6 on 2021-02-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='center.course'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='center.course'),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='center.course'),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='studntsnames',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='center.studentsdetail'),
        ),
    ]
